# Generated by Django 4.0.4 on 2022-04-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
