# Generated by Django 4.0.4 on 2022-04-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_student_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
    ]
