# Generated by Django 4.0.4 on 2022-04-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_rename_name_student_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
